project_id = "iqsvqkvfknvqcuksbzmo"

[functions.find-food-banks]
verify_jwt = false

[functions.find-grocery-stores]
verify_jwt = false

[functions.scan-receipt]
verify_jwt = false

[functions.chat]
verify_jwt = false

[functions.convert-image]
verify_jwt = false

[functions.send-contact-email]
verify_jwt = false
